# Vectores y sus operaciones

In [1]:
# Vectores
# Crear un vector con una lista de python

v1py = [1,2,3]
v2py = [4,5,6]

v1py + v2py

[1, 2, 3, 4, 5, 6]

In [2]:
7 * v1py

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
# Importar numpy que es la libreria matematica que me permite utilizar los objetos algebraicos

import numpy as np

In [4]:
# Crear un array de numpy

v1np = np.array([1,2,3]) 
v2np = np.array(v2py) # np.array([4,5,6])

In [5]:
#Suma de vectores
v1np + v2np

array([5, 7, 9])

In [6]:
#Resta de vectores
v1np - v2np

array([-3, -3, -3])

In [7]:
#Multiplicación por escalar
7 * v1np

array([ 7, 14, 21])

In [10]:
# Funcion para crear vectores con 1's

vunos = np.ones(7)
vunos

array([1., 1., 1., 1., 1., 1., 1.])

In [20]:
# Crear vectores por un rango definido

vrange = np.arange(8,16)
vrange

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
# Producto punto en numpy
np.dot(v1np,v2np)

32

In [24]:
# Producto punto con sum (función nativa de python)
sum(v1np*v2np)

32

In [26]:
# Ejemplo de vectores ortogonales o perpendiculares
v1 = np.array([3,4])
v2 = np.array([4,-3])

np.dot(v1,v2)

0

In [28]:
# Ejemplo de cálculo de norma del vector
v3 = np.array([1,2,3,4])
np.linalg.norm(v3)

5.477225575051661

# Matrices

In [30]:
A = np.array([[1,3,2],[1,0,0],[1,2,2]]) # Para creear matrices van dentro de una lista, y son listas separadas por comas

A

array([[1, 3, 2],
       [1, 0, 0],
       [1, 2, 2]])

In [31]:
B = np.array([[1,0,5],
              [7,5,0],
              [2,1,1]])
B

array([[1, 0, 5],
       [7, 5, 0],
       [2, 1, 1]])

In [32]:
A + B

array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

In [33]:
A - B

array([[ 0,  3, -3],
       [-6, -5,  0],
       [-1,  1,  1]])

In [34]:
A * 5

array([[ 5, 15, 10],
       [ 5,  0,  0],
       [ 5, 10, 10]])

In [35]:
# Para ver la dimensión de mi matriz (Cuantas columnas, cuantos renglones)
A.shape

(3, 3)

In [37]:
# Cuantos elementos 
A.size

9

In [38]:
# Multiplicación de matrices
A = np.arange(1,13).reshape(3,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
B = np.arange(8).reshape(4,2)
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [41]:
A @ B #El arroba es el simbolo que usa numpy para realizar la multiplicación de matrices

array([[ 40,  50],
       [ 88, 114],
       [136, 178]])

In [42]:
B @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [45]:
# Creando una matriz identidad
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [46]:
C = np.array([[4,7],
              [2,6]])

In [47]:
I @ C

array([[4., 7.],
       [2., 6.]])

In [48]:
# Calculo del determinante
np.linalg.det(C)

10.000000000000002

In [49]:
# Calculo del determinante
E = np.array([[1,2,3],
              [4,1,2],
              [3,4,1]])
np.linalg.det(E)

36.0

In [51]:
# Matriz transpuesta
F = np.arange(6).reshape(3,2)
F

array([[0, 1],
       [2, 3],
       [4, 5]])

In [52]:
np.transpose(F)

array([[0, 2, 4],
       [1, 3, 5]])

In [53]:
# Matriz inversa
inv = np.linalg.inv(C)
inv

array([[ 0.6, -0.7],
       [-0.2,  0.4]])